version: '3.9'

services:
  #mongo_db:
  #  container_name: mongo_backiii
  #  image: mongo:latest
  #  ports:
  #    - 27017:27017

  api:
    container_name: api_backiii
    build: .
    ports:
      - 8003:8003
    environment:
      #MONGO_URI: mongodb://mongo_db:27017/backiii
      MONGO_URI: mongodb+srv://userCoder:passCoder@cluster0.2ltylis.mongodb.net/proyecto-back-iii?retryWrites=true&w=majority&appName=Cluster0
